# Generated by Django 5.2.8 on 2025-12-13 20:14

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicacionPostParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentacionFetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReanimacionNeonatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('basica', 'Básica'), ('avanzada', 'Avanzada')], default='basica', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRecienNacido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('fecha_hora', models.DateTimeField()),
                ('nombre_completo_madre', models.CharField(blank=True, max_length=150)),
                ('peso', models.PositiveIntegerField()),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4)),
                ('apgar_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('perimetro_cefalico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('perimetro_toraxico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('c_2480', models.PositiveSmallIntegerField()),
                ('destino_rn', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('alojamiento_conjunto', models.BooleanField()),
                ('apego_canguro', models.BooleanField()),
                ('lactante_60', models.BooleanField()),
                ('apego_tunel', models.BooleanField()),
                ('gases_de_cordon', models.BooleanField()),
                ('destino', models.CharField(choices=[('alojamiento', 'Alojamiento conjunto'), ('uci', 'UCI Neonatal'), ('uti', 'UTI Neonatal'), ('fallecido', 'Fallecido')], default='alojamiento', max_length=50)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.parto')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('presentacion_fetal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recien_nacidos.presentacionfetal')),
            ],
            options={
                'verbose_name': 'historical recien nacido',
                'verbose_name_plural': 'historical recien nacidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_hora', models.DateTimeField()),
                ('nombre_completo_madre', models.CharField(blank=True, max_length=150)),
                ('peso', models.PositiveIntegerField()),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4)),
                ('apgar_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('perimetro_cefalico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('perimetro_toraxico', models.DecimalField(decimal_places=1, max_digits=4)),
                ('c_2480', models.PositiveSmallIntegerField()),
                ('destino_rn', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('alojamiento_conjunto', models.BooleanField()),
                ('apego_canguro', models.BooleanField()),
                ('lactante_60', models.BooleanField()),
                ('apego_tunel', models.BooleanField()),
                ('gases_de_cordon', models.BooleanField()),
                ('destino', models.CharField(choices=[('alojamiento', 'Alojamiento conjunto'), ('uci', 'UCI Neonatal'), ('uti', 'UTI Neonatal'), ('fallecido', 'Fallecido')], default='alojamiento', max_length=50)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=10)),
                ('complicaciones_postparto', models.ManyToManyField(related_name='rns', to='recien_nacidos.complicacionpostparto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rns', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rns', to='partos.parto')),
                ('presentacion_fetal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rns', to='recien_nacidos.presentacionfetal')),
                ('reanimaciones_neonatales', models.ManyToManyField(related_name='rns', to='recien_nacidos.reanimacionneonatal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rns_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('reaccion_adversa', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacunaciones', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='partos.profesional')),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='recien_nacidos.reciennacido')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacunas', to='recien_nacidos.tipovacuna')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacunaciones_actualizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
