# Generated by Django 5.2.8 on 2025-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='complicaciones_postparto',
            field=models.ManyToManyField(blank=True, related_name='rns', to='recien_nacidos.complicacionpostparto'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='reanimaciones_neonatales',
            field=models.ManyToManyField(blank=True, related_name='rns', to='recien_nacidos.reanimacionneonatal'),
        ),
    ]
