# Generated by Django 5.2.8 on 2025-12-13 20:14

import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalgesiaParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitada', models.BooleanField(default=False)),
                ('indicada', models.BooleanField(default=False)),
                ('administrada', models.BooleanField(default=False)),
                ('tiempo_espera_minutos', models.PositiveIntegerField(blank=True, help_text='Tiempo entre indicación y administración', null=True)),
                ('dosis', models.CharField(max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoRobson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalParto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('hora_inicio', models.DateTimeField()),
                ('numero_aro', models.PositiveSmallIntegerField(default=0)),
                ('n_tactos_vaginales', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('rotura_membrana', models.CharField(choices=[('espontanea', 'Espontánea'), ('artificial', 'Artificial')], default='espontanea', max_length=50)),
                ('estado', models.CharField(choices=[('terminado', 'Terminado'), ('ingreso', 'Ingreso'), ('activo', 'Activo'), ('expulsivo', 'Expulsivo'), ('alumbramiento', 'Alumbramiento'), ('puerperio', 'Puerperio Inmediato')], default='ingreso', max_length=30)),
                ('posicion', models.CharField(choices=[('semisentada', 'Semisentada'), ('sentada', 'Sentada'), ('litotomia', 'Litotomia'), ('dorsal', 'D.Dorsal'), ('cuadrupeda', 'Cuadrúpeda'), ('lateral', 'D.Lateral'), ('de pie', 'De Pie'), ('cuclillas', 'Cuclillas'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('tipo_regimen', models.CharField(choices=[('cero', 'Cero'), ('liquido', 'Liquido'), ('comun', 'Comun'), ('otro', 'Otro')], default='cero', max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('tiempo_membrana_rota', models.DurationField()),
                ('tiempo_dilatacion', models.DurationField()),
                ('tiempo_expulsivo', models.DurationField()),
                ('edad_madre', models.PositiveSmallIntegerField()),
                ('monitor', models.BooleanField(default=False)),
                ('entrega_placenta', models.BooleanField(default=False)),
                ('acompaniante', models.BooleanField(default=False)),
                ('ttc', models.BooleanField(default=False)),
                ('induccion', models.BooleanField(default=False)),
                ('aceleracion', models.BooleanField(default=False)),
                ('oxitocina_profilactica', models.BooleanField(default=False)),
                ('uso_sala_saip', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical parto',
                'verbose_name_plural': 'historical partos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hora_inicio', models.DateTimeField()),
                ('numero_aro', models.PositiveSmallIntegerField(default=0)),
                ('n_tactos_vaginales', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('rotura_membrana', models.CharField(choices=[('espontanea', 'Espontánea'), ('artificial', 'Artificial')], default='espontanea', max_length=50)),
                ('estado', models.CharField(choices=[('terminado', 'Terminado'), ('ingreso', 'Ingreso'), ('activo', 'Activo'), ('expulsivo', 'Expulsivo'), ('alumbramiento', 'Alumbramiento'), ('puerperio', 'Puerperio Inmediato')], default='ingreso', max_length=30)),
                ('posicion', models.CharField(choices=[('semisentada', 'Semisentada'), ('sentada', 'Sentada'), ('litotomia', 'Litotomia'), ('dorsal', 'D.Dorsal'), ('cuadrupeda', 'Cuadrúpeda'), ('lateral', 'D.Lateral'), ('de pie', 'De Pie'), ('cuclillas', 'Cuclillas'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('tipo_regimen', models.CharField(choices=[('cero', 'Cero'), ('liquido', 'Liquido'), ('comun', 'Comun'), ('otro', 'Otro')], default='cero', max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('tiempo_membrana_rota', models.DurationField()),
                ('tiempo_dilatacion', models.DurationField()),
                ('tiempo_expulsivo', models.DurationField()),
                ('edad_madre', models.PositiveSmallIntegerField()),
                ('monitor', models.BooleanField(default=False)),
                ('entrega_placenta', models.BooleanField(default=False)),
                ('acompaniante', models.BooleanField(default=False)),
                ('ttc', models.BooleanField(default=False)),
                ('induccion', models.BooleanField(default=False)),
                ('aceleracion', models.BooleanField(default=False)),
                ('oxitocina_profilactica', models.BooleanField(default=False)),
                ('uso_sala_saip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(max_length=45)),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('tipo', models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('enfermera', 'Enfermera'), ('ayudante', 'Ayudante'), ('matrona', 'Matrona'), ('medico', 'Medico Obstetra'), ('anestesiologo', 'Anestesiologo'), ('pediatra', 'Pediatra o Neonatólogo')], default='enfermera', max_length=30)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puerperio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_perine', models.CharField(choices=[('indemne', 'Indemne'), ('g1', 'Desgarro G1'), ('g2', 'Desgarro G2'), ('g3a', 'Desgarro G3 A'), ('g3b', 'Desgarro G3 B'), ('g3c', 'Desgarro G3 C'), ('g4', 'Desgarro G4'), ('fisura', 'Fisura'), ('episiotomia', 'Episiotomia')], default='indemne', max_length=30)),
                ('esterilizacion', models.BooleanField(default=False)),
                ('revision', models.BooleanField(default=False)),
                ('inercia_uterina', models.BooleanField(default=False)),
                ('restos_placenta', models.BooleanField(default=False)),
                ('trauma', models.BooleanField(default=False)),
                ('alteracion_coagulacion', models.BooleanField(default=False)),
                ('manejo_qirurgico_inercia_ut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnalgesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViaNacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
