# Generated by Django 5.2.8 on 2025-12-13 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_initial'),
        ('partos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analgesiaparto',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analgesias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='gestacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.gestacion'),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='grupo_robson',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.gruporobson'),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parto',
            name='complicaciones',
            field=models.ManyToManyField(related_name='partos', to='partos.complicacion'),
        ),
        migrations.AddField(
            model_name='parto',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parto',
            name='gestacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parto', to='pacientes.gestacion'),
        ),
        migrations.AddField(
            model_name='parto',
            name='grupo_robson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.gruporobson'),
        ),
        migrations.AddField(
            model_name='parto',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacion',
            name='parto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='partos.parto'),
        ),
        migrations.AddField(
            model_name='analgesiaparto',
            name='parto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analgesias', to='partos.parto'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='partos.profesional'),
        ),
        migrations.AddField(
            model_name='puerperio',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puerperios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puerperio',
            name='parto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='puerperio', to='partos.parto'),
        ),
        migrations.AddField(
            model_name='puerperio',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puerperios_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analgesiaparto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partos.tipoanalgesia'),
        ),
        migrations.AddField(
            model_name='parto',
            name='tipo_de_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.tipodeingreso'),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='tipo_de_ingreso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.tipodeingreso'),
        ),
        migrations.AddField(
            model_name='parto',
            name='via_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='partos.vianacimiento'),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='via_nacimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.vianacimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('parto', 'profesional')},
        ),
    ]
