# Generated by Django 5.2.8 on 2025-12-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparto',
            name='inicio_parto',
            field=models.CharField(choices=[('espontanea', 'Espontánea'), ('inducido_far', 'Inducido Farmacologicamente'), ('inducido_mec', 'Inducido Mecanicamente'), ('conducido', 'Conduccion Oxitóxica')], default='espontanea', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalparto',
            name='tipo_acompaniante',
            field=models.CharField(choices=[('sin', 'Sin Acompaniante'), ('trab_parto', 'Durante Trabajo de Parto'), ('solo_expul', 'Solo Expulsivo')], default='sin', max_length=50),
        ),
        migrations.AddField(
            model_name='parto',
            name='inicio_parto',
            field=models.CharField(choices=[('espontanea', 'Espontánea'), ('inducido_far', 'Inducido Farmacologicamente'), ('inducido_mec', 'Inducido Mecanicamente'), ('conducido', 'Conduccion Oxitóxica')], default='espontanea', max_length=50),
        ),
        migrations.AddField(
            model_name='parto',
            name='tipo_acompaniante',
            field=models.CharField(choices=[('sin', 'Sin Acompaniante'), ('trab_parto', 'Durante Trabajo de Parto'), ('solo_expul', 'Solo Expulsivo')], default='sin', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalparto',
            name='aceleracion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparto',
            name='acompaniante',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparto',
            name='induccion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='aceleracion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='acompaniante',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='induccion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
