# Generated by Django 5.2.8 on 2025-12-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0003_historicalparto_inicio_parto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparto',
            name='libertad_movimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='libertad_movimiento',
            field=models.BooleanField(default=False),
        ),
    ]
