# Generated by Django 5.2.8 on 2025-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0004_historicalparto_libertad_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto',
            name='complicaciones',
            field=models.ManyToManyField(blank=True, related_name='partos', to='partos.complicacion'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='rut',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
