# Generated by Django 5.2.8 on 2025-12-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0005_alter_parto_complicaciones_alter_profesional_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparto',
            name='semanas_gestacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='semanas_gestacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
