# Generated by Django 5.2.8 on 2026-01-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0006_historicalparto_semanas_gestacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analgesiaparto',
            unique_together={('parto', 'tipo')},
        ),
    ]
