# Generated by Django 5.2.8 on 2025-12-13 20:14

import apps.pacientes.fields.order_field
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_fetos', models.PositiveSmallIntegerField()),
                ('riesgo', models.CharField(choices=[('bajo', 'Bajo Riesgo'), ('medio', 'Riesgo Moderado'), ('alto', 'Alto Riesgo')], default='bajo', max_length=10)),
                ('estado', models.CharField(choices=[('terminada', 'Terminada'), ('aborto', 'Aborto'), ('curso', 'En Curso')], default='curso', max_length=10)),
                ('origen_datacion', models.CharField(choices=[('fur', 'FUR'), ('eco', 'ECO'), ('sin', 'Sin Datacion Disponible')], default='sin', help_text='La fecha de inicio de gestación se tomará según el origen que seleccione: FUR o ECO.', max_length=3)),
                ('fur', models.DateField(blank=True, null=True)),
                ('fecha_eco', models.DateField(blank=True, null=True)),
                ('semanas_eco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dias_eco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_inicio_gestacion', models.DateField(blank=True, null=True)),
                ('numero_gestacion', apps.pacientes.fields.order_field.OrderField(blank=True)),
                ('enfermedad_cardiaca', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gestacion',
                'verbose_name_plural': 'Gestaciones',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGestacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('numero_fetos', models.PositiveSmallIntegerField()),
                ('riesgo', models.CharField(choices=[('bajo', 'Bajo Riesgo'), ('medio', 'Riesgo Moderado'), ('alto', 'Alto Riesgo')], default='bajo', max_length=10)),
                ('estado', models.CharField(choices=[('terminada', 'Terminada'), ('aborto', 'Aborto'), ('curso', 'En Curso')], default='curso', max_length=10)),
                ('origen_datacion', models.CharField(choices=[('fur', 'FUR'), ('eco', 'ECO'), ('sin', 'Sin Datacion Disponible')], default='sin', help_text='La fecha de inicio de gestación se tomará según el origen que seleccione: FUR o ECO.', max_length=3)),
                ('fur', models.DateField(blank=True, null=True)),
                ('fecha_eco', models.DateField(blank=True, null=True)),
                ('semanas_eco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dias_eco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_inicio_gestacion', models.DateField(blank=True, null=True)),
                ('numero_gestacion', apps.pacientes.fields.order_field.OrderField(blank=True)),
                ('enfermedad_cardiaca', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Gestacion',
                'verbose_name_plural': 'historical Gestaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaciente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(choices=[('RUT', 'Rut'), ('PAS', 'Pasaporte'), ('EXT', 'Documento extranjero'), ('TMP', 'Sin documento / Temporal')], default='RUT', max_length=3)),
                ('identificacion', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('descapacitado', models.BooleanField(default=False)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('privada_de_libertad', models.BooleanField(default=False)),
                ('transexual', models.BooleanField(default=False)),
                ('plan_de_parto', models.BooleanField(default=False)),
                ('visita_guiada', models.BooleanField(default=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('actividad', models.CharField(choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta')], default='baja', max_length=9)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical paciente',
                'verbose_name_plural': 'historical pacientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(choices=[('RUT', 'Rut'), ('PAS', 'Pasaporte'), ('EXT', 'Documento extranjero'), ('TMP', 'Sin documento / Temporal')], default='RUT', max_length=3)),
                ('identificacion', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('descapacitado', models.BooleanField(default=False)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('privada_de_libertad', models.BooleanField(default=False)),
                ('transexual', models.BooleanField(default=False)),
                ('plan_de_parto', models.BooleanField(default=False)),
                ('visita_guiada', models.BooleanField(default=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('actividad', models.CharField(choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta')], default='baja', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='TestHepatitisB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField(help_text='Fecha en la que se tomo el examen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lugar_toma', models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12)),
                ('antibiotico', models.BooleanField(default=False)),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
                ('derivacion_especialista', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSgb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField(help_text='Fecha en la que se tomo el examen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lugar_toma', models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12)),
                ('antibiotico', models.BooleanField(default=False)),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestVdrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField(help_text='Fecha en la que se tomo el examen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lugar_toma', models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12)),
                ('antibiotico', models.BooleanField(default=False)),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestVih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('positivo', 'Reactivo'), ('negativo', 'No Reactivo')], default='negativo', max_length=15)),
                ('fecha_toma', models.DateField(help_text='Fecha en la que se tomo el examen')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('lugar_toma', models.CharField(choices=[('preparto', 'Preparto'), ('sala_parto', 'Sala de Partos'), ('urgencia', 'Urgencias')], default='preparto', max_length=12)),
                ('antibiotico', models.BooleanField(default=False)),
                ('durante_parto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('orden', apps.pacientes.fields.order_field.OrderField()),
                ('n_aro', models.PositiveIntegerField()),
                ('trimestre', models.CharField(choices=[('1', 'Primer Trimestre (0-12 semanas)'), ('2', 'Segundo Trimestre (13-27 semanas)'), ('3', 'Tercer Trimestre (28-40 semanas)')], default='1', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cesfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.comuna')),
            ],
            options={
                'ordering': ['comuna__nombre', 'nombre'],
            },
        ),
    ]
