# Generated by Django 5.2.8 on 2025-12-13 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gestacion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestaciones_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgestacion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgestacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgestacion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='cesfam',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.cesfam'),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='comuna',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.comuna'),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.nacionalidad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cesfam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.cesfam'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.comuna'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='pacientes.nacionalidad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgestacion',
            name='paciente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='gestacion',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestaciones', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='testhepatitisb',
            name='gestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion'),
        ),
        migrations.AddField(
            model_name='testsgb',
            name='gestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion'),
        ),
        migrations.AddField(
            model_name='testvdrl',
            name='gestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion'),
        ),
        migrations.AddField(
            model_name='testvih',
            name='gestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='pacientes.gestacion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='pacientes.tipopaciente'),
        ),
        migrations.AddField(
            model_name='historicalpaciente',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.tipopaciente'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['documento', 'identificacion'], name='pacientes_p_documen_5ec0fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('documento', 'identificacion')},
        ),
    ]
