# Generated by Django 5.2.8 on 2025-12-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestacion',
            name='semanas_gestacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgestacion',
            name='semanas_gestacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
