# Generated by Django 5.2.8 on 2025-12-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_gestacion_semanas_gestacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestacion',
            name='semanas_gestacion',
        ),
        migrations.RemoveField(
            model_name='historicalgestacion',
            name='semanas_gestacion',
        ),
    ]
