# Generated by Django 5.2.8 on 2025-12-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_gestacion_semanas_gestacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'otro')], default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'otro')], default='F', max_length=10),
        ),
    ]
